### ISSUE TITLE
Error when processing more than 500 files in the directory

### ISSUE THREAD

**Issue by Xsenix** [kekal/telegra.ph-album-creator#3]
It is known that telegra.ph the article is able to handle a certain limit, the main problem is the error output from the side telegra.ph because the number of files is limited to five hundred files at a time.

The main solution that I have reached at the moment is to create a variable that is responsible for the number of files in each of the submerged directories.

As an alternative, I also considered adding a timeout using the time.sleep() function when processing the "try again later" error, but I do not yet know how to solve error 10054 (The remote host forcibly terminated the existing connection) after the time of the operation.

**Comment by Xsenix** [comment]
you can create a variable `MAX_FILES_TO_PROCESS` and add a couple of lines to `def analyze_folder_content():`
```
max_files_to_process = MAX_FILES_TO_PROCESS
__file_names = __file_names[:max_files_to_process]
```
it will look like this
```
def analyze_folder_content(__directory):
    logger.info("Searching for images...")
    __file_names = get_files_in_folder(__directory)
    max_files_to_process = MAX_FILES_TO_PROCESS
    __file_names = __file_names[:max_files_to_process]
    for file_name in __file_names:
        logger.info("   " + file_name + " found")

    logger.info('\n   ' + str(len(__file_names)) + " files found.\n")

    return __file_names
```

**Comment by kekal** [comment]
> It is known that telegra.ph the article is able to handle a certain limit, the main problem is the error output from the side telegra.ph because the number of files is limited to five hundred files at a time.


There is no such thing as files in an article, since the API does not support linking media to a page.  Each object is uploaded to the server independently and is in not referenced with other objects uploaded under the same token.  Actually you don’t have to create an article at all, but simply keep the files.  The limitation you are observing is a default shaping of the server load. It has a time-defined basis.  That is, you can download a certain number of objects in half an hour or a certain number of bytes in half an hour.

You can, of course, make the script in such a way that it works without interruption, but I was not able to find out the exact shaping conditions. In addition, they seem to be dynamic. A deliberately large timeout will help, but will greatly slow down normal work with small albums.
